#FROM node:6 as node-build
#WORKDIR /build
#COPY ./client/package.json .
#RUN npm -g install -g grunt-cli && npm install
#COPY ./client .
#RUN grunt build --server='http://localhost:8080/api' --ws='ws://localhost:8080/ws'

FROM nginx
COPY client/dist /opt/superdesk/client/dist
COPY nginx.conf /etc/nginx/nginx.conf





