# import base image
FROM ubuntu:18.04

ENV TZ=Europe/Vienna
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US
ENV LC_ALL en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# install system-wide dependencies,
# python3 and the build-time dependencies for c modules
RUN apt-get update && \
 apt-get install -y --no-install-recommends \
python3 python3-dev python3-pip python3-lxml python3-setuptools \
build-essential libffi-dev git \
libtiff5-dev libjpeg8-dev zlib1g-dev tzdata \
libfreetype6-dev liblcms2-dev libwebp-dev \
curl libfontconfig nodejs npm nginx locales \
&& echo "\ndaemon off;" >> /etc/nginx/nginx.conf \
&& rm /etc/nginx/sites-enabled/default

RUN npm install -g npm
RUN npm -v
RUN npm -g install grunt-cli

# Set the locale
# RUN locale-gen en_US.UTF-8

#RUN sudo dpkg-reconfigure --non-interactive tzdata
# setup the environment
WORKDIR /opt/superdesk/
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/superdesk_vhost.conf /etc/nginx/sites-enabled/superdesk.conf
COPY ./docker/start.sh /opt/superdesk/start.sh
CMD /opt/superdesk/start.sh

# client ports
EXPOSE 9000
EXPOSE 80
# server ports
EXPOSE 5000
EXPOSE 5100

# set env vars for the server
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT "False"
ENV CELERYBEAT_SCHEDULE_FILENAME /tmp/celerybeatschedule.db

# install server dependencies
COPY ./server/requirements.txt /tmp/requirements.txt
RUN cd /tmp && pip3 install -U -r /tmp/requirements.txt

# install client dependencies
COPY ./client/package.json /opt/superdesk/client/
RUN cd ./client && npm install

# copy server sources
COPY ./server /opt/superdesk

# copy client sources
COPY ./client /opt/superdesk/client

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-magic

# TODO: this is hack to update basic themes during bamboo deployment
COPY ./server/liveblog/themes/themes_assets/ /opt/superdesk/themes_assets/

RUN cd ./client && npm i
